import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {BsInstagram, BsLinkedin, BsGithub} from 'react-icons/bs';
import Image from "next/image";
import Logo from '../public/Mask group(1).png'
import Coverart from '../public/Cover_art.png'
import design from '../public/design.png'
import Laptopcode from '../public/LaptopCode.png'
import Pencil from '../public/pencil.gif'
import Figma from '../public/figma.gif'
import Canva from '../public/canva.png'
import Photoshop from '../public/photoshop.gif'
import Bootstrap from '../public/bootstrap.png'
import Cryptaul from '../public/Cryptaul.png'
import BedandBones from '../public/BedandBones.png'
import SamuraiCode from '../public/Samurai-Code-Logo.png'
import {useState} from 'react';


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Precursor Designz Website Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-700">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
          <div className="relative flex justify-between">
            <Image alt='#' src={Logo} width={"50%"}/>
          </div>
          <ul className="flex item-center">
            <li>
              <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer"/>
            </li>
            <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
            href="#">
              Linkedin
              </a>
            </li>
          </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-blue-800 font-medium md:text-6xl">Jeremiah Harriott</h2>
            <h3 className="text-2xl py-2 md:text-3xl">Web Developer & Designer</h3>
            <p className="text-med py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto">Give me your ideas, and ill do the rest!</p>
          </div>
          <div className="text-5xl py-5 flex justify-center gap-16 text-blue-800">
            <BsLinkedin />
            <BsInstagram />
            <BsGithub />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image alt='#' src={Coverart}  />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl text-center py-1">Services I can offer?</h3>
            <p className="text-md py-2 leading-8 text-gray-800 md:text">As a freelance web developer and designer with 2 years experience, I,ve decided to start my own company
              helping business owners, agencies and even startup companies have the amazing website they deserve. This includes the designing of brands
              and full development for;
              </p>
            <ul className="text-center text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              <li>Logos</li>
              <li>E-Commerce Websites</li>
              <li>Portfolio Websites</li>
              <li>Bookings Websites</li>
              <li>Personal blogs</li>
              <li>Business websites</li>
            </ul>
          </div>
          <div className="lg:flex gap-10">
          <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image alt='#' src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2" >
                Beautiful Designz
                </h3>
              <p className="py-2">
                Conspiring & building the best suited designs for you or your companys needs and ideas.
              </p>
              <h4 className="py-4 text-green-700">Design Tools</h4>
              <p className="text-gray-800 py-1">Figma<Image alt='#' src={Figma} width={30} height={30} /></p>
              <p className="text-gray-800 py-1">Canva<Image alt='#' src={Canva} width={30} height={30} /></p>
              <p className="text-gray-800 py-1">Photoshop<Image alt='#' src={Photoshop} width={30} height={30} /></p>
              <p className="text-gray-800 py-1">Bootstrap<Image alt='#' src={Bootstrap} width={23} height={23} /></p>
              <p className="text-gray-800 py-1">Sketch<Image alt='#' src={Pencil} width={30} height={30} /></p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white">
              <Image alt='#' src={Laptopcode} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2" >
                Beautiful Designz
                </h3>
              <p className="py-2">
                Conspiring & building the best suited designs for you or your companys needs and ideas.
              </p>
              <h4 className="py-4 text-green-700">Design Tools</h4>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Canva</p>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Bootstrap</p>
              <p className="text-gray-800 py-1">Sketch</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white">
            <Image alt='#' src={Laptopcode} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2" >
                Beautiful Designz
                </h3>
              <p className="py-2">
                Conspiring & building the best suited designs for you or your companys needs and ideas.
              </p>
              <h4 className="py-4 text-green-700">Design Tools</h4>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Canva</p>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Bootstrap</p>
              <p className="text-gray-800 py-1">Sketch</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">Portfolio</h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap ">
            <div className="basis-1/3 flex-1">
              <Image alt='#'
               src={Cryptaul}
               className="rounded-lg object-cover"
               width={"100%"}
               height={"100%"}
               layout="responsive" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image alt='#'
               src={BedandBones}
               className="rounded-lg object-cover"
               width={'100%'}
               height={'100%'}
               layout="responsive" />
            </div>
            <div className="basis-1/3 flex-1">
              <Image alt='#'
               src={SamuraiCode}
               className="rounded-lg object-cover"
               width={'100%'}
               height={'100%'}
               layout="responsive" />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
